### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by Blahfoot** [Dwedit/goombacolor#3]
This is my first time trying to truly use github so perhaps there is something I'm not aware of. My computer is indicating there is a virus detected in the goombacolor_2019_5_4.zip file. Any help on this would be greatly appreciated! :)

**Comment by Dwedit** [comment]
There's a couple of old visual basic programs in there, but they aren't viruses.

**Comment by Blahfoot** [comment]
Thanks for the heads up. I'll dig for a workaround to get my antivirus software to allow it through.
